export type { ClientWebAuthnConfig } from './hooks/useRegister'
export { useRegister } from './hooks/useRegister'
export { useLogin } from './hooks/useLogin'
export { useSession, type WebAuthnSession } from './hooks/useSession'
export { useWebAuthn } from './hooks/useWebAuthn'
export { RegisterForm } from './components/RegisterForm'
export { LoginForm } from './components/LoginForm'
